SELECT 
npc_instances.instance_id
,npc_instances.instance_name
,npc_notifications.object_id
,obj1.objecttype_id
,obj1.name1 AS host_name
,obj1.name2 AS service_description
,obj2.name1 AS contact_name
,npc_contactnotifications.start_time AS notification_start_time
,npc_contactnotifications.start_time_usec AS notification_start_time_usec
,npc_contactnotifications.end_time AS notification_end_time
,npc_contactnotifications.end_time_usec AS notification_end_time_usec
,obj3.name1 AS notification_command_name
,npc_contactnotificationmethods.*
FROM `npc_contactnotificationmethods`
JOIN npc_contactnotifications ON npc_contactnotificationmethods.contactnotification_id=npc_contactnotifications.contactnotification_id
JOIN npc_notifications ON npc_contactnotifications.notification_id=npc_notifications.notification_id
LEFT JOIN npc_objects as obj1 ON npc_notifications.object_id=obj1.object_id
LEFT JOIN npc_objects as obj2 ON npc_contactnotifications.contact_object_id=obj2.object_id
LEFT JOIN npc_objects as obj3 ON npc_contactnotificationmethods.command_object_id=obj3.object_id
LEFT JOIN npc_instances ON npc_notifications.instance_id=npc_instances.instance_id
ORDER BY start_time DESC, start_time_usec DESC

