<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNpcAcknowledgements extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('npc_acknowledgements');
    $this->hasColumn('acknowledgement_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => true,
  'notnull' => true,
  'autoincrement' => true,
));
    $this->hasColumn('instance_id', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('entry_time', 'timestamp', null, array (
  'alltypes' => 
  [],
  'ntype' => 'datetime',
  'values' => 
  [],
  'primary' => false,
  'default' => '0000-00-00 00:00:00',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('entry_time_usec', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('acknowledgement_type', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('object_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('state', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('author_name', 'string', 64, array (
  'alltypes' => 
  [],
  'ntype' => 'varchar(64)',
  'fixed' => false,
  'values' => 
  [],
  'primary' => false,
  'default' => '',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('comment_data', 'string', 255, array (
  'alltypes' => 
  [],
  'ntype' => 'varchar(255)',
  'fixed' => false,
  'values' => 
  [],
  'primary' => false,
  'default' => '',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('is_sticky', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('persistent_comment', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('notify_contacts', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
  }


}