<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNpcSettings extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('npc_settings');
    $this->hasColumn('user_id', 'integer', 3, array (
  'alltypes' => 
  [],
  'ntype' => 'mediumint(8) unsigned',
  'unsigned' => 1,
  'values' => 
  [],
  'primary' => true,
  'default' => '',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('settings', 'string', null, array (
  'alltypes' => 
  [],
  'ntype' => 'text',
  'fixed' => false,
  'values' => 
  [],
  'primary' => false,
  'notnull' => false,
  'autoincrement' => false,
));
  }


}