<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNpcHostParenthosts extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('npc_host_parenthosts');
    $this->hasColumn('host_parenthost_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => true,
  'notnull' => true,
  'autoincrement' => true,
));
    $this->hasColumn('instance_id', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('host_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('parent_host_object_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
  }


}