<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNpcDbversion extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('npc_dbversion');
    $this->hasColumn('name', 'string', 10, array (
  'alltypes' => 
  array (
    0 => 'string',
  ),
  'ntype' => 'varchar(10)',
  'fixed' => false,
  'values' => 
  array (
  ),
  'primary' => false,
  'default' => '',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('version', 'string', 10, array (
  'alltypes' => 
  array (
    0 => 'string',
  ),
  'ntype' => 'varchar(10)',
  'fixed' => false,
  'values' => 
  array (
  ),
  'primary' => false,
  'default' => '',
  'notnull' => true,
  'autoincrement' => false,
));
  }


}