<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNpcHostescalations extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('npc_hostescalations');
    $this->hasColumn('hostescalation_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => true,
  'notnull' => true,
  'autoincrement' => true,
));
    $this->hasColumn('instance_id', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('config_type', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('host_object_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('timeperiod_object_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('first_notification', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('last_notification', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('notification_interval', 'float', null, array (
  'alltypes' => 
  [],
  'ntype' => 'double',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('escalate_on_recovery', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('escalate_on_down', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('escalate_on_unreachable', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
  }


}