<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNpcCustomvariablestatus extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('npc_customvariablestatus');
    $this->hasColumn('customvariablestatus_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => true,
  'notnull' => true,
  'autoincrement' => true,
));
    $this->hasColumn('instance_id', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('object_id', 'integer', 4, array (
  'alltypes' => 
  [],
  'ntype' => 'int(11)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('status_update_time', 'timestamp', null, array (
  'alltypes' => 
  [],
  'ntype' => 'datetime',
  'values' => 
  [],
  'primary' => false,
  'default' => '0000-00-00 00:00:00',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('has_been_modified', 'integer', 2, array (
  'alltypes' => 
  [],
  'ntype' => 'smallint(6)',
  'unsigned' => 0,
  'values' => 
  [],
  'primary' => false,
  'default' => '0',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('varname', 'string', 255, array (
  'alltypes' => 
  [],
  'ntype' => 'varchar(255)',
  'fixed' => false,
  'values' => 
  [],
  'primary' => false,
  'default' => '',
  'notnull' => true,
  'autoincrement' => false,
));
    $this->hasColumn('varvalue', 'string', 255, array (
  'alltypes' => 
  [],
  'ntype' => 'varchar(255)',
  'fixed' => false,
  'values' => 
  [],
  'primary' => false,
  'default' => '',
  'notnull' => true,
  'autoincrement' => false,
));
  }


}