<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcComments extends BaseNpcComments
{

    public function setUp()
    {

        $this->hasOne('NpcServices as Service', array('local' => 'object_id', 'foreign' => 'object_id', 'refClass' => 'NpcObjects'));



    }

}
