<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcHost extends BaseNpcHost
{
    public function setUp()
    {
        $this->hasOne('NpcObjects as Object', array('local' => 'host_object_id', 'foreign' => 'object_id'));
        $this->hasMany('NpcServices as Service', array('local' => 'host_object_id', 'foreign' => 'host_object_id'));
    }
}
