<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcHostchecks extends BaseNpcHostchecks
{
    public function setUp()
    {
        $this->hasOne('NpcHosts as Host', []);
    }
}
