<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcHostchecks extends BaseNpcHostchecks
{
    public function setUp()
    {
        $this->hasOne('NpcHosts as Host', array('local' => 'host_object_id', 'foreign' => 'host_object_id'));
    }
}
