<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcHostgroups extends BaseNpcHostgroups
{
    public function setUp()
    {
        $this->hasOne('NpcObjects as Object', []);
        $this->hasOne('NpcInstances as Instance', []);
        $this->hasMany('NpcHostgroupMembers as HostgroupMembers', []);
        $this->hasMany('NpcHosts as Hosts', []);
        $this->hasMany('NpcHoststatus as Hoststatus', []);
    }
}
