<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcNotifications extends BaseNpcNotifications
{
    public function setUp()
    {
        $this->hasOne('NpcObjects as Object', []);
        $this->hasOne('NpcInstances as Instance', []);
        $this->hasOne('NpcServices as Service', []);
        $this->hasOne('NpcHosts as Host', []);
    }
}
