<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcObjects extends BaseNpcObjects
{

    public function setUp()
    {

        //$this->hasMany('NpcServices as Services', []);
        //$this->hasMany('NpcHosts as Hosts', []);
        //$this->hasMany('NpcComments as Comments', []);

    }



}
