<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcObjects extends BaseNpcObjects
{

    public function setUp()
    {

        //$this->hasMany('NpcServices as Services', array('foreign' => 'service_object_id', 'local' => 'object_id'));
        //$this->hasMany('NpcHosts as Hosts', array('foreign' => 'host_object_id', 'local' => 'object_id'));
        //$this->hasMany('NpcComments as Comments', array('foreign' => 'object_id', 'local' => 'object_id'));

    }



}
