<?php

declare(strict_types=1);

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NpcServicegroups extends BaseNpcServicegroups
{
    public function setUp()
    {
        $this->hasOne('NpcObjects as Object', []);
        $this->hasOne('NpcInstances as Instance', []);
        $this->hasMany('NpcServicegroupMembers as ServicegroupMembers', []);
        $this->hasMany('NpcServices as Services', []);
        $this->hasMany('NpcServicestatus as Servicestatus', []);
    }
}
